# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Seth Gower
email: seth@sethgower.com

#write html inside the double quotes to display in jumbotron
description: "<h3>Hello, world!</h3><h1>Seth Gower's Blog</h1>"



baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sethgower.com" # the base hostname & protocol for your site
twitter_username: gower_seth
github_username:  sethgower

# Build settings
markdown: kramdown
